#连接数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/apsfc?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
  #访问静态页面
  mvc:
    view:
      prefix: /public/
      suffix: .jsp
  web:
    resources:
      static-locations: classpath:/META-INF/resources

